import { IHero } from '@/types';
import { HeroesPrimaryAttribute, HeroesRoles } from '@/enum/heroes';

export const ATTRIBUTE_TITLE_MAPPER = {
  [HeroesPrimaryAttribute.STRENGTH]: 'Strength',
  [HeroesPrimaryAttribute.AGILITY]: 'Agility',
  [HeroesPrimaryAttribute.INTELLIGENCE]: 'Intelligence',
};

export const NO_HERO = 'noHero';

export const HEROES: IHero[] = [
  {
    id: 1,
    name: 'npc_dota_hero_antimage',
    localized_name: 'Anti-Mage',
    primary_attr: HeroesPrimaryAttribute.AGILITY,
    attack_type: 'Melee',
    roles: [HeroesRoles.CARRY, HeroesRoles.ESCAPE, HeroesRoles.NUKER],
    legs: 2,
  },
  {
    id: 2,
    name: 'npc_dota_hero_axe',
    localized_name: 'Axe',
    primary_attr: HeroesPrimaryAttribute.STRENGTH,
    attack_type: 'Melee',
    roles: [
      HeroesRoles.INITIATOR,
      HeroesRoles.DURABLE,
      HeroesRoles.DISABLER,
      HeroesRoles.JUNGLER,
      HeroesRoles.CARRY,
    ],
    legs: 2,
  },
  {
    id: 3,
    name: 'npc_dota_hero_bane',
    localized_name: 'Bane',
    primary_attr: HeroesPrimaryAttribute.INTELLIGENCE,
    attack_type: 'Ranged',
    roles: [
      HeroesRoles.SUPPORT,
      HeroesRoles.DISABLER,
      HeroesRoles.NUKER,
      HeroesRoles.DURABLE,
    ],
    legs: 4,
  },
  {
    id: 4,
    name: 'npc_dota_hero_bloodseeker',
    localized_name: 'Bloodseeker',
    primary_attr: HeroesPrimaryAttribute.AGILITY,
    attack_type: 'Melee',
    roles: [
      HeroesRoles.CARRY,
      HeroesRoles.DISABLER,
      HeroesRoles.JUNGLER,
      HeroesRoles.NUKER,
      HeroesRoles.INITIATOR,
    ],
    legs: 2,
  },
  {
    id: 5,
    name: 'npc_dota_hero_crystal_maiden',
    localized_name: 'Crystal Maiden',
    primary_attr: HeroesPrimaryAttribute.INTELLIGENCE,
    attack_type: 'Ranged',
    roles: [
      HeroesRoles.SUPPORT,
      HeroesRoles.DISABLER,
      HeroesRoles.NUKER,
      HeroesRoles.JUNGLER,
    ],
    legs: 2,
  },
  {
    id: 6,
    name: 'npc_dota_hero_drow_ranger',
    localized_name: 'Drow Ranger',
    primary_attr: HeroesPrimaryAttribute.AGILITY,
    attack_type: 'Ranged',
    roles: [HeroesRoles.CARRY, HeroesRoles.DISABLER, HeroesRoles.PUSHER],
    legs: 2,
  },
  {
    id: 7,
    name: 'npc_dota_hero_earthshaker',
    localized_name: 'Earthshaker',
    primary_attr: HeroesPrimaryAttribute.STRENGTH,
    attack_type: 'Melee',
    roles: [
      HeroesRoles.SUPPORT,
      HeroesRoles.INITIATOR,
      HeroesRoles.DISABLER,
      HeroesRoles.NUKER,
    ],
    legs: 2,
  },
  {
    id: 8,
    name: 'npc_dota_hero_juggernaut',
    localized_name: 'Juggernaut',
    primary_attr: HeroesPrimaryAttribute.AGILITY,
    attack_type: 'Melee',
    roles: [HeroesRoles.CARRY, HeroesRoles.PUSHER, HeroesRoles.ESCAPE],
    legs: 2,
  },
  {
    id: 9,
    name: 'npc_dota_hero_mirana',
    localized_name: 'Mirana',
    primary_attr: HeroesPrimaryAttribute.AGILITY,
    attack_type: 'Ranged',
    roles: [
      HeroesRoles.CARRY,
      HeroesRoles.SUPPORT,
      HeroesRoles.ESCAPE,
      HeroesRoles.NUKER,
      HeroesRoles.DISABLER,
    ],
    legs: 2,
  },
  {
    id: 10,
    name: 'npc_dota_hero_morphling',
    localized_name: 'Morphling',
    primary_attr: HeroesPrimaryAttribute.AGILITY,
    attack_type: 'Ranged',
    roles: [
      HeroesRoles.CARRY,
      HeroesRoles.ESCAPE,
      HeroesRoles.DURABLE,
      HeroesRoles.NUKER,
      HeroesRoles.DISABLER,
    ],
    legs: 0,
  },
  {
    id: 11,
    name: 'npc_dota_hero_nevermore',
    localized_name: 'Shadow Fiend',
    primary_attr: HeroesPrimaryAttribute.AGILITY,
    attack_type: 'Ranged',
    roles: [HeroesRoles.CARRY, HeroesRoles.NUKER],
    legs: 0,
  },
  {
    id: 12,
    name: 'npc_dota_hero_phantom_lancer',
    localized_name: 'Phantom Lancer',
    primary_attr: HeroesPrimaryAttribute.AGILITY,
    attack_type: 'Melee',
    roles: [HeroesRoles.CARRY, HeroesRoles.ESCAPE, HeroesRoles.PUSHER, HeroesRoles.NUKER],
    legs: 2,
  },
  {
    id: 13,
    name: 'npc_dota_hero_puck',
    localized_name: 'Puck',
    primary_attr: HeroesPrimaryAttribute.INTELLIGENCE,
    attack_type: 'Ranged',
    roles: [
      HeroesRoles.INITIATOR,
      HeroesRoles.DISABLER,
      HeroesRoles.ESCAPE,
      HeroesRoles.NUKER,
    ],
    legs: 2,
  },
  {
    id: 14,
    name: 'npc_dota_hero_pudge',
    localized_name: 'Pudge',
    primary_attr: HeroesPrimaryAttribute.STRENGTH,
    attack_type: 'Melee',
    roles: [
      HeroesRoles.DISABLER,
      HeroesRoles.INITIATOR,
      HeroesRoles.DURABLE,
      HeroesRoles.NUKER,
    ],
    legs: 2,
  },
  {
    id: 15,
    name: 'npc_dota_hero_razor',
    localized_name: 'Razor',
    primary_attr: HeroesPrimaryAttribute.AGILITY,
    attack_type: 'Ranged',
    roles: [
      HeroesRoles.CARRY,
      HeroesRoles.DURABLE,
      HeroesRoles.NUKER,
      HeroesRoles.PUSHER,
    ],
    legs: 0,
  },
  {
    id: 16,
    name: 'npc_dota_hero_sand_king',
    localized_name: 'Sand King',
    primary_attr: HeroesPrimaryAttribute.STRENGTH,
    attack_type: 'Melee',
    roles: [
      HeroesRoles.INITIATOR,
      HeroesRoles.DISABLER,
      HeroesRoles.SUPPORT,
      HeroesRoles.NUKER,
      HeroesRoles.ESCAPE,
      HeroesRoles.JUNGLER,
    ],
    legs: 6,
  },
  {
    id: 17,
    name: 'npc_dota_hero_storm_spirit',
    localized_name: 'Storm Spirit',
    primary_attr: HeroesPrimaryAttribute.INTELLIGENCE,
    attack_type: 'Ranged',
    roles: [
      HeroesRoles.CARRY,
      HeroesRoles.ESCAPE,
      HeroesRoles.NUKER,
      HeroesRoles.INITIATOR,
      HeroesRoles.DISABLER,
    ],
    legs: 2,
  },
  {
    id: 18,
    name: 'npc_dota_hero_sven',
    localized_name: 'Sven',
    primary_attr: HeroesPrimaryAttribute.STRENGTH,
    attack_type: 'Melee',
    roles: [
      HeroesRoles.CARRY,
      HeroesRoles.DISABLER,
      HeroesRoles.INITIATOR,
      HeroesRoles.DURABLE,
      HeroesRoles.NUKER,
    ],
    legs: 2,
  },
  {
    id: 19,
    name: 'npc_dota_hero_tiny',
    localized_name: 'Tiny',
    primary_attr: HeroesPrimaryAttribute.STRENGTH,
    attack_type: 'Melee',
    roles: [
      HeroesRoles.CARRY,
      HeroesRoles.NUKER,
      HeroesRoles.PUSHER,
      HeroesRoles.INITIATOR,
      HeroesRoles.DURABLE,
      HeroesRoles.DISABLER,
    ],
    legs: 2,
  },
  {
    id: 20,
    name: 'npc_dota_hero_vengefulspirit',
    localized_name: 'Vengeful Spirit',
    primary_attr: HeroesPrimaryAttribute.AGILITY,
    attack_type: 'Ranged',
    roles: [
      HeroesRoles.SUPPORT,
      HeroesRoles.INITIATOR,
      HeroesRoles.DISABLER,
      HeroesRoles.NUKER,
      HeroesRoles.ESCAPE,
    ],
    legs: 2,
  },
  {
    id: 21,
    name: 'npc_dota_hero_windrunner',
    localized_name: 'Windranger',
    primary_attr: HeroesPrimaryAttribute.INTELLIGENCE,
    attack_type: 'Ranged',
    roles: [
      HeroesRoles.CARRY,
      HeroesRoles.SUPPORT,
      HeroesRoles.DISABLER,
      HeroesRoles.ESCAPE,
      HeroesRoles.NUKER,
    ],
    legs: 2,
  },
  {
    id: 22,
    name: 'npc_dota_hero_zuus',
    localized_name: 'Zeus',
    primary_attr: HeroesPrimaryAttribute.INTELLIGENCE,
    attack_type: 'Ranged',
    roles: [HeroesRoles.NUKER, HeroesRoles.CARRY],
    legs: 2,
  },
  {
    id: 23,
    name: 'npc_dota_hero_kunkka',
    localized_name: 'Kunkka',
    primary_attr: HeroesPrimaryAttribute.STRENGTH,
    attack_type: 'Melee',
    roles: [
      HeroesRoles.CARRY,
      HeroesRoles.SUPPORT,
      HeroesRoles.DISABLER,
      HeroesRoles.INITIATOR,
      HeroesRoles.DURABLE,
      HeroesRoles.NUKER,
    ],
    legs: 2,
  },
  {
    id: 25,
    name: 'npc_dota_hero_lina',
    localized_name: 'Lina',
    primary_attr: HeroesPrimaryAttribute.INTELLIGENCE,
    attack_type: 'Ranged',
    roles: [
      HeroesRoles.SUPPORT,
      HeroesRoles.CARRY,
      HeroesRoles.NUKER,
      HeroesRoles.DISABLER,
    ],
    legs: 2,
  },
  {
    id: 26,
    name: 'npc_dota_hero_lion',
    localized_name: 'Lion',
    primary_attr: HeroesPrimaryAttribute.INTELLIGENCE,
    attack_type: 'Ranged',
    roles: [
      HeroesRoles.SUPPORT,
      HeroesRoles.DISABLER,
      HeroesRoles.NUKER,
      HeroesRoles.INITIATOR,
    ],
    legs: 2,
  },
  {
    id: 27,
    name: 'npc_dota_hero_shadow_shaman',
    localized_name: 'Shadow Shaman',
    primary_attr: HeroesPrimaryAttribute.INTELLIGENCE,
    attack_type: 'Ranged',
    roles: [
      HeroesRoles.SUPPORT,
      HeroesRoles.PUSHER,
      HeroesRoles.DISABLER,
      HeroesRoles.NUKER,
      HeroesRoles.INITIATOR,
    ],
    legs: 2,
  },
  {
    id: 28,
    name: 'npc_dota_hero_slardar',
    localized_name: 'Slardar',
    primary_attr: HeroesPrimaryAttribute.STRENGTH,
    attack_type: 'Melee',
    roles: [
      HeroesRoles.CARRY,
      HeroesRoles.DURABLE,
      HeroesRoles.INITIATOR,
      HeroesRoles.DISABLER,
      HeroesRoles.ESCAPE,
    ],
    legs: 0,
  },
  {
    id: 29,
    name: 'npc_dota_hero_tidehunter',
    localized_name: 'Tidehunter',
    primary_attr: HeroesPrimaryAttribute.STRENGTH,
    attack_type: 'Melee',
    roles: [
      HeroesRoles.INITIATOR,
      HeroesRoles.DURABLE,
      HeroesRoles.DISABLER,
      HeroesRoles.NUKER,
      HeroesRoles.CARRY,
    ],
    legs: 2,
  },
  {
    id: 30,
    name: 'npc_dota_hero_witch_doctor',
    localized_name: 'Witch Doctor',
    primary_attr: HeroesPrimaryAttribute.INTELLIGENCE,
    attack_type: 'Ranged',
    roles: [HeroesRoles.SUPPORT, HeroesRoles.NUKER, HeroesRoles.DISABLER],
    legs: 2,
  },
  {
    id: 31,
    name: 'npc_dota_hero_lich',
    localized_name: 'Lich',
    primary_attr: HeroesPrimaryAttribute.INTELLIGENCE,
    attack_type: 'Ranged',
    roles: [HeroesRoles.SUPPORT, HeroesRoles.NUKER],
    legs: 2,
  },
  {
    id: 32,
    name: 'npc_dota_hero_riki',
    localized_name: 'Riki',
    primary_attr: HeroesPrimaryAttribute.AGILITY,
    attack_type: 'Melee',
    roles: [HeroesRoles.CARRY, HeroesRoles.ESCAPE, HeroesRoles.DISABLER],
    legs: 2,
  },
  {
    id: 33,
    name: 'npc_dota_hero_enigma',
    localized_name: 'Enigma',
    primary_attr: HeroesPrimaryAttribute.INTELLIGENCE,
    attack_type: 'Ranged',
    roles: [
      HeroesRoles.DISABLER,
      HeroesRoles.JUNGLER,
      HeroesRoles.INITIATOR,
      HeroesRoles.PUSHER,
    ],
    legs: 0,
  },
  {
    id: 34,
    name: 'npc_dota_hero_tinker',
    localized_name: 'Tinker',
    primary_attr: HeroesPrimaryAttribute.INTELLIGENCE,
    attack_type: 'Ranged',
    roles: [HeroesRoles.CARRY, HeroesRoles.NUKER, HeroesRoles.PUSHER],
    legs: 2,
  },
  {
    id: 35,
    name: 'npc_dota_hero_sniper',
    localized_name: 'Sniper',
    primary_attr: HeroesPrimaryAttribute.AGILITY,
    attack_type: 'Ranged',
    roles: [HeroesRoles.CARRY, HeroesRoles.NUKER],
    legs: 2,
  },
  {
    id: 36,
    name: 'npc_dota_hero_necrolyte',
    localized_name: 'Necrophos',
    primary_attr: HeroesPrimaryAttribute.INTELLIGENCE,
    attack_type: 'Ranged',
    roles: [
      HeroesRoles.CARRY,
      HeroesRoles.NUKER,
      HeroesRoles.DURABLE,
      HeroesRoles.DISABLER,
    ],
    legs: 2,
  },
  {
    id: 37,
    name: 'npc_dota_hero_warlock',
    localized_name: 'Warlock',
    primary_attr: HeroesPrimaryAttribute.INTELLIGENCE,
    attack_type: 'Ranged',
    roles: [HeroesRoles.SUPPORT, HeroesRoles.INITIATOR, HeroesRoles.DISABLER],
    legs: 2,
  },
  {
    id: 38,
    name: 'npc_dota_hero_beastmaster',
    localized_name: 'Beastmaster',
    primary_attr: HeroesPrimaryAttribute.STRENGTH,
    attack_type: 'Melee',
    roles: [
      HeroesRoles.INITIATOR,
      HeroesRoles.DISABLER,
      HeroesRoles.DURABLE,
      HeroesRoles.NUKER,
    ],
    legs: 2,
  },
  {
    id: 39,
    name: 'npc_dota_hero_queenofpain',
    localized_name: 'Queen of Pain',
    primary_attr: HeroesPrimaryAttribute.INTELLIGENCE,
    attack_type: 'Ranged',
    roles: [HeroesRoles.CARRY, HeroesRoles.NUKER, HeroesRoles.ESCAPE],
    legs: 2,
  },
  {
    id: 40,
    name: 'npc_dota_hero_venomancer',
    localized_name: 'Venomancer',
    primary_attr: HeroesPrimaryAttribute.AGILITY,
    attack_type: 'Ranged',
    roles: [
      HeroesRoles.SUPPORT,
      HeroesRoles.NUKER,
      HeroesRoles.INITIATOR,
      HeroesRoles.PUSHER,
      HeroesRoles.DISABLER,
    ],
    legs: 0,
  },
  {
    id: 41,
    name: 'npc_dota_hero_faceless_void',
    localized_name: 'Faceless Void',
    primary_attr: HeroesPrimaryAttribute.AGILITY,
    attack_type: 'Melee',
    roles: [
      HeroesRoles.CARRY,
      HeroesRoles.INITIATOR,
      HeroesRoles.DISABLER,
      HeroesRoles.ESCAPE,
      HeroesRoles.DURABLE,
    ],
    legs: 2,
  },
  {
    id: 42,
    name: 'npc_dota_hero_skeleton_king',
    localized_name: 'Wraith King',
    primary_attr: HeroesPrimaryAttribute.STRENGTH,
    attack_type: 'Melee',
    roles: [
      HeroesRoles.CARRY,
      HeroesRoles.SUPPORT,
      HeroesRoles.DURABLE,
      HeroesRoles.DISABLER,
      HeroesRoles.INITIATOR,
    ],
    legs: 2,
  },
  {
    id: 43,
    name: 'npc_dota_hero_death_prophet',
    localized_name: 'Death Prophet',
    primary_attr: HeroesPrimaryAttribute.INTELLIGENCE,
    attack_type: 'Ranged',
    roles: [
      HeroesRoles.CARRY,
      HeroesRoles.PUSHER,
      HeroesRoles.NUKER,
      HeroesRoles.DISABLER,
    ],
    legs: 2,
  },
  {
    id: 44,
    name: 'npc_dota_hero_phantom_assassin',
    localized_name: 'Phantom Assassin',
    primary_attr: HeroesPrimaryAttribute.AGILITY,
    attack_type: 'Melee',
    roles: [HeroesRoles.CARRY, HeroesRoles.ESCAPE],
    legs: 2,
  },
  {
    id: 45,
    name: 'npc_dota_hero_pugna',
    localized_name: 'Pugna',
    primary_attr: HeroesPrimaryAttribute.INTELLIGENCE,
    attack_type: 'Ranged',
    roles: [HeroesRoles.NUKER, HeroesRoles.PUSHER],
    legs: 2,
  },
  {
    id: 46,
    name: 'npc_dota_hero_templar_assassin',
    localized_name: 'Templar Assassin',
    primary_attr: HeroesPrimaryAttribute.AGILITY,
    attack_type: 'Ranged',
    roles: [HeroesRoles.CARRY, HeroesRoles.ESCAPE],
    legs: 2,
  },
  {
    id: 47,
    name: 'npc_dota_hero_viper',
    localized_name: 'Viper',
    primary_attr: HeroesPrimaryAttribute.AGILITY,
    attack_type: 'Ranged',
    roles: [
      HeroesRoles.CARRY,
      HeroesRoles.DURABLE,
      HeroesRoles.INITIATOR,
      HeroesRoles.DISABLER,
    ],
    legs: 0,
  },
  {
    id: 48,
    name: 'npc_dota_hero_luna',
    localized_name: 'Luna',
    primary_attr: HeroesPrimaryAttribute.AGILITY,
    attack_type: 'Ranged',
    roles: [HeroesRoles.CARRY, HeroesRoles.NUKER, HeroesRoles.PUSHER],
    legs: 2,
  },
  {
    id: 49,
    name: 'npc_dota_hero_dragon_knight',
    localized_name: 'Dragon Knight',
    primary_attr: HeroesPrimaryAttribute.STRENGTH,
    attack_type: 'Melee',
    roles: [
      HeroesRoles.CARRY,
      HeroesRoles.PUSHER,
      HeroesRoles.DURABLE,
      HeroesRoles.DISABLER,
      HeroesRoles.INITIATOR,
      HeroesRoles.NUKER,
    ],
    legs: 2,
  },
  {
    id: 50,
    name: 'npc_dota_hero_dazzle',
    localized_name: 'Dazzle',
    primary_attr: HeroesPrimaryAttribute.INTELLIGENCE,
    attack_type: 'Ranged',
    roles: [HeroesRoles.SUPPORT, HeroesRoles.NUKER, HeroesRoles.DISABLER],
    legs: 2,
  },
  {
    id: 51,
    name: 'npc_dota_hero_rattletrap',
    localized_name: 'Clockwerk',
    primary_attr: HeroesPrimaryAttribute.STRENGTH,
    attack_type: 'Melee',
    roles: [
      HeroesRoles.INITIATOR,
      HeroesRoles.DISABLER,
      HeroesRoles.DURABLE,
      HeroesRoles.NUKER,
    ],
    legs: 2,
  },
  {
    id: 52,
    name: 'npc_dota_hero_leshrac',
    localized_name: 'Leshrac',
    primary_attr: HeroesPrimaryAttribute.INTELLIGENCE,
    attack_type: 'Ranged',
    roles: [
      HeroesRoles.CARRY,
      HeroesRoles.SUPPORT,
      HeroesRoles.NUKER,
      HeroesRoles.PUSHER,
      HeroesRoles.DISABLER,
    ],
    legs: 4,
  },
  {
    id: 53,
    name: 'npc_dota_hero_furion',
    localized_name: "Nature's Prophet",
    primary_attr: HeroesPrimaryAttribute.INTELLIGENCE,
    attack_type: 'Ranged',
    roles: [
      HeroesRoles.CARRY,
      HeroesRoles.JUNGLER,
      HeroesRoles.PUSHER,
      HeroesRoles.ESCAPE,
      HeroesRoles.NUKER,
    ],
    legs: 2,
  },
  {
    id: 54,
    name: 'npc_dota_hero_life_stealer',
    localized_name: 'Lifestealer',
    primary_attr: HeroesPrimaryAttribute.STRENGTH,
    attack_type: 'Melee',
    roles: [
      HeroesRoles.CARRY,
      HeroesRoles.DURABLE,
      HeroesRoles.JUNGLER,
      HeroesRoles.ESCAPE,
      HeroesRoles.DISABLER,
    ],
    legs: 2,
  },
  {
    id: 55,
    name: 'npc_dota_hero_dark_seer',
    localized_name: 'Dark Seer',
    primary_attr: HeroesPrimaryAttribute.INTELLIGENCE,
    attack_type: 'Melee',
    roles: [
      HeroesRoles.INITIATOR,
      HeroesRoles.JUNGLER,
      HeroesRoles.ESCAPE,
      HeroesRoles.DISABLER,
    ],
    legs: 2,
  },
  {
    id: 56,
    name: 'npc_dota_hero_clinkz',
    localized_name: 'Clinkz',
    primary_attr: HeroesPrimaryAttribute.AGILITY,
    attack_type: 'Ranged',
    roles: [HeroesRoles.CARRY, HeroesRoles.ESCAPE, HeroesRoles.PUSHER],
    legs: 2,
  },
  {
    id: 57,
    name: 'npc_dota_hero_omniknight',
    localized_name: 'Omniknight',
    primary_attr: HeroesPrimaryAttribute.STRENGTH,
    attack_type: 'Melee',
    roles: [HeroesRoles.SUPPORT, HeroesRoles.DURABLE, HeroesRoles.NUKER],
    legs: 2,
  },
  {
    id: 58,
    name: 'npc_dota_hero_enchantress',
    localized_name: 'Enchantress',
    primary_attr: HeroesPrimaryAttribute.INTELLIGENCE,
    attack_type: 'Ranged',
    roles: [
      HeroesRoles.SUPPORT,
      HeroesRoles.JUNGLER,
      HeroesRoles.PUSHER,
      HeroesRoles.DURABLE,
      HeroesRoles.DISABLER,
    ],
    legs: 4,
  },
  {
    id: 59,
    name: 'npc_dota_hero_huskar',
    localized_name: 'Huskar',
    primary_attr: HeroesPrimaryAttribute.STRENGTH,
    attack_type: 'Ranged',
    roles: [HeroesRoles.CARRY, HeroesRoles.DURABLE, HeroesRoles.INITIATOR],
    legs: 2,
  },
  {
    id: 60,
    name: 'npc_dota_hero_night_stalker',
    localized_name: 'Night Stalker',
    primary_attr: HeroesPrimaryAttribute.STRENGTH,
    attack_type: 'Melee',
    roles: [
      HeroesRoles.CARRY,
      HeroesRoles.INITIATOR,
      HeroesRoles.DURABLE,
      HeroesRoles.DISABLER,
      HeroesRoles.NUKER,
    ],
    legs: 2,
  },
  {
    id: 61,
    name: 'npc_dota_hero_broodmother',
    localized_name: 'Broodmother',
    primary_attr: HeroesPrimaryAttribute.AGILITY,
    attack_type: 'Melee',
    roles: [HeroesRoles.CARRY, HeroesRoles.PUSHER, HeroesRoles.ESCAPE, HeroesRoles.NUKER],
    legs: 8,
  },
  {
    id: 62,
    name: 'npc_dota_hero_bounty_hunter',
    localized_name: 'Bounty Hunter',
    primary_attr: HeroesPrimaryAttribute.AGILITY,
    attack_type: 'Melee',
    roles: [HeroesRoles.ESCAPE, HeroesRoles.NUKER],
    legs: 2,
  },
  {
    id: 63,
    name: 'npc_dota_hero_weaver',
    localized_name: 'Weaver',
    primary_attr: HeroesPrimaryAttribute.AGILITY,
    attack_type: 'Ranged',
    roles: [HeroesRoles.CARRY, HeroesRoles.ESCAPE],
    legs: 4,
  },
  {
    id: 64,
    name: 'npc_dota_hero_jakiro',
    localized_name: 'Jakiro',
    primary_attr: HeroesPrimaryAttribute.INTELLIGENCE,
    attack_type: 'Ranged',
    roles: [
      HeroesRoles.SUPPORT,
      HeroesRoles.NUKER,
      HeroesRoles.PUSHER,
      HeroesRoles.DISABLER,
    ],
    legs: 2,
  },
  {
    id: 65,
    name: 'npc_dota_hero_batrider',
    localized_name: 'Batrider',
    primary_attr: HeroesPrimaryAttribute.INTELLIGENCE,
    attack_type: 'Ranged',
    roles: [
      HeroesRoles.INITIATOR,
      HeroesRoles.JUNGLER,
      HeroesRoles.DISABLER,
      HeroesRoles.ESCAPE,
    ],
    legs: 2,
  },
  {
    id: 66,
    name: 'npc_dota_hero_chen',
    localized_name: 'Chen',
    primary_attr: HeroesPrimaryAttribute.INTELLIGENCE,
    attack_type: 'Ranged',
    roles: [HeroesRoles.SUPPORT, HeroesRoles.JUNGLER, HeroesRoles.PUSHER],
    legs: 2,
  },
  {
    id: 67,
    name: 'npc_dota_hero_spectre',
    localized_name: 'Spectre',
    primary_attr: HeroesPrimaryAttribute.AGILITY,
    attack_type: 'Melee',
    roles: [HeroesRoles.CARRY, HeroesRoles.DURABLE, HeroesRoles.ESCAPE],
    legs: 0,
  },
  {
    id: 68,
    name: 'npc_dota_hero_ancient_apparition',
    localized_name: 'Ancient Apparition',
    primary_attr: HeroesPrimaryAttribute.INTELLIGENCE,
    attack_type: 'Ranged',
    roles: [HeroesRoles.SUPPORT, HeroesRoles.DISABLER, HeroesRoles.NUKER],
    legs: 0,
  },
  {
    id: 69,
    name: 'npc_dota_hero_doom_bringer',
    localized_name: 'Doom',
    primary_attr: HeroesPrimaryAttribute.STRENGTH,
    attack_type: 'Melee',
    roles: [
      HeroesRoles.CARRY,
      HeroesRoles.DISABLER,
      HeroesRoles.INITIATOR,
      HeroesRoles.DURABLE,
      HeroesRoles.NUKER,
    ],
    legs: 2,
  },
  {
    id: 70,
    name: 'npc_dota_hero_ursa',
    localized_name: 'Ursa',
    primary_attr: HeroesPrimaryAttribute.AGILITY,
    attack_type: 'Melee',
    roles: [
      HeroesRoles.CARRY,
      HeroesRoles.JUNGLER,
      HeroesRoles.DURABLE,
      HeroesRoles.DISABLER,
    ],
    legs: 2,
  },
  {
    id: 71,
    name: 'npc_dota_hero_spirit_breaker',
    localized_name: 'Spirit Breaker',
    primary_attr: HeroesPrimaryAttribute.STRENGTH,
    attack_type: 'Melee',
    roles: [
      HeroesRoles.CARRY,
      HeroesRoles.INITIATOR,
      HeroesRoles.DISABLER,
      HeroesRoles.DURABLE,
      HeroesRoles.ESCAPE,
    ],
    legs: 2,
  },
  {
    id: 72,
    name: 'npc_dota_hero_gyrocopter',
    localized_name: 'Gyrocopter',
    primary_attr: HeroesPrimaryAttribute.AGILITY,
    attack_type: 'Ranged',
    roles: [HeroesRoles.CARRY, HeroesRoles.NUKER, HeroesRoles.DISABLER],
    legs: 2,
  },
  {
    id: 73,
    name: 'npc_dota_hero_alchemist',
    localized_name: 'Alchemist',
    primary_attr: HeroesPrimaryAttribute.STRENGTH,
    attack_type: 'Melee',
    roles: [
      HeroesRoles.CARRY,
      HeroesRoles.SUPPORT,
      HeroesRoles.DURABLE,
      HeroesRoles.DISABLER,
      HeroesRoles.INITIATOR,
      HeroesRoles.NUKER,
    ],
    legs: 2,
  },
  {
    id: 74,
    name: 'npc_dota_hero_invoker',
    localized_name: 'Invoker',
    primary_attr: HeroesPrimaryAttribute.INTELLIGENCE,
    attack_type: 'Ranged',
    roles: [
      HeroesRoles.CARRY,
      HeroesRoles.NUKER,
      HeroesRoles.DISABLER,
      HeroesRoles.ESCAPE,
      HeroesRoles.PUSHER,
    ],
    legs: 2,
  },
  {
    id: 75,
    name: 'npc_dota_hero_silencer',
    localized_name: 'Silencer',
    primary_attr: HeroesPrimaryAttribute.INTELLIGENCE,
    attack_type: 'Ranged',
    roles: [
      HeroesRoles.CARRY,
      HeroesRoles.SUPPORT,
      HeroesRoles.DISABLER,
      HeroesRoles.INITIATOR,
      HeroesRoles.NUKER,
    ],
    legs: 2,
  },
  {
    id: 76,
    name: 'npc_dota_hero_obsidian_destroyer',
    localized_name: 'Outworld Destroyer',
    primary_attr: HeroesPrimaryAttribute.INTELLIGENCE,
    attack_type: 'Ranged',
    roles: [HeroesRoles.CARRY, HeroesRoles.NUKER, HeroesRoles.DISABLER],
    legs: 4,
  },
  {
    id: 77,
    name: 'npc_dota_hero_lycan',
    localized_name: 'Lycan',
    primary_attr: HeroesPrimaryAttribute.STRENGTH,
    attack_type: 'Melee',
    roles: [
      HeroesRoles.CARRY,
      HeroesRoles.PUSHER,
      HeroesRoles.JUNGLER,
      HeroesRoles.DURABLE,
      HeroesRoles.ESCAPE,
    ],
    legs: 2,
  },
  {
    id: 78,
    name: 'npc_dota_hero_brewmaster',
    localized_name: 'Brewmaster',
    primary_attr: HeroesPrimaryAttribute.STRENGTH,
    attack_type: 'Melee',
    roles: [
      HeroesRoles.CARRY,
      HeroesRoles.INITIATOR,
      HeroesRoles.DURABLE,
      HeroesRoles.DISABLER,
      HeroesRoles.NUKER,
    ],
    legs: 2,
  },
  {
    id: 79,
    name: 'npc_dota_hero_shadow_demon',
    localized_name: 'Shadow Demon',
    primary_attr: HeroesPrimaryAttribute.INTELLIGENCE,
    attack_type: 'Ranged',
    roles: [
      HeroesRoles.SUPPORT,
      HeroesRoles.DISABLER,
      HeroesRoles.INITIATOR,
      HeroesRoles.NUKER,
    ],
    legs: 2,
  },
  {
    id: 80,
    name: 'npc_dota_hero_lone_druid',
    localized_name: 'Lone Druid',
    primary_attr: HeroesPrimaryAttribute.AGILITY,
    attack_type: 'Ranged',
    roles: [
      HeroesRoles.CARRY,
      HeroesRoles.PUSHER,
      HeroesRoles.JUNGLER,
      HeroesRoles.DURABLE,
    ],
    legs: 2,
  },
  {
    id: 81,
    name: 'npc_dota_hero_chaos_knight',
    localized_name: 'Chaos Knight',
    primary_attr: HeroesPrimaryAttribute.STRENGTH,
    attack_type: 'Melee',
    roles: [
      HeroesRoles.CARRY,
      HeroesRoles.DISABLER,
      HeroesRoles.DURABLE,
      HeroesRoles.PUSHER,
      HeroesRoles.INITIATOR,
    ],
    legs: 2,
  },
  {
    id: 82,
    name: 'npc_dota_hero_meepo',
    localized_name: 'Meepo',
    primary_attr: HeroesPrimaryAttribute.AGILITY,
    attack_type: 'Melee',
    roles: [
      HeroesRoles.CARRY,
      HeroesRoles.ESCAPE,
      HeroesRoles.NUKER,
      HeroesRoles.DISABLER,
      HeroesRoles.INITIATOR,
      HeroesRoles.PUSHER,
    ],
    legs: 2,
  },
  {
    id: 83,
    name: 'npc_dota_hero_treant',
    localized_name: 'Treant Protector',
    primary_attr: HeroesPrimaryAttribute.STRENGTH,
    attack_type: 'Melee',
    roles: [
      HeroesRoles.SUPPORT,
      HeroesRoles.INITIATOR,
      HeroesRoles.DURABLE,
      HeroesRoles.DISABLER,
      HeroesRoles.ESCAPE,
    ],
    legs: 2,
  },
  {
    id: 84,
    name: 'npc_dota_hero_ogre_magi',
    localized_name: 'Ogre Magi',
    primary_attr: HeroesPrimaryAttribute.INTELLIGENCE,
    attack_type: 'Melee',
    roles: [
      HeroesRoles.SUPPORT,
      HeroesRoles.NUKER,
      HeroesRoles.DISABLER,
      HeroesRoles.DURABLE,
      HeroesRoles.INITIATOR,
    ],
    legs: 2,
  },
  {
    id: 85,
    name: 'npc_dota_hero_undying',
    localized_name: 'Undying',
    primary_attr: HeroesPrimaryAttribute.STRENGTH,
    attack_type: 'Melee',
    roles: [
      HeroesRoles.SUPPORT,
      HeroesRoles.DURABLE,
      HeroesRoles.DISABLER,
      HeroesRoles.NUKER,
    ],
    legs: 2,
  },
  {
    id: 86,
    name: 'npc_dota_hero_rubick',
    localized_name: 'Rubick',
    primary_attr: HeroesPrimaryAttribute.INTELLIGENCE,
    attack_type: 'Ranged',
    roles: [HeroesRoles.SUPPORT, HeroesRoles.DISABLER, HeroesRoles.NUKER],
    legs: 2,
  },
  {
    id: 87,
    name: 'npc_dota_hero_disruptor',
    localized_name: 'Disruptor',
    primary_attr: HeroesPrimaryAttribute.INTELLIGENCE,
    attack_type: 'Ranged',
    roles: [
      HeroesRoles.SUPPORT,
      HeroesRoles.DISABLER,
      HeroesRoles.NUKER,
      HeroesRoles.INITIATOR,
    ],
    legs: 2,
  },
  {
    id: 88,
    name: 'npc_dota_hero_nyx_assassin',
    localized_name: 'Nyx Assassin',
    primary_attr: HeroesPrimaryAttribute.AGILITY,
    attack_type: 'Melee',
    roles: [
      HeroesRoles.DISABLER,
      HeroesRoles.NUKER,
      HeroesRoles.INITIATOR,
      HeroesRoles.ESCAPE,
    ],
    legs: 6,
  },
  {
    id: 89,
    name: 'npc_dota_hero_naga_siren',
    localized_name: 'Naga Siren',
    primary_attr: HeroesPrimaryAttribute.AGILITY,
    attack_type: 'Melee',
    roles: [
      HeroesRoles.CARRY,
      HeroesRoles.SUPPORT,
      HeroesRoles.PUSHER,
      HeroesRoles.DISABLER,
      HeroesRoles.INITIATOR,
      HeroesRoles.ESCAPE,
    ],
    legs: 0,
  },
  {
    id: 90,
    name: 'npc_dota_hero_keeper_of_the_light',
    localized_name: 'Keeper of the Light',
    primary_attr: HeroesPrimaryAttribute.INTELLIGENCE,
    attack_type: 'Ranged',
    roles: [
      HeroesRoles.SUPPORT,
      HeroesRoles.NUKER,
      HeroesRoles.DISABLER,
      HeroesRoles.JUNGLER,
    ],
    legs: 2,
  },
  {
    id: 91,
    name: 'npc_dota_hero_wisp',
    localized_name: 'Io',
    primary_attr: HeroesPrimaryAttribute.STRENGTH,
    attack_type: 'Ranged',
    roles: [HeroesRoles.SUPPORT, HeroesRoles.ESCAPE, HeroesRoles.NUKER],
    legs: 0,
  },
  {
    id: 92,
    name: 'npc_dota_hero_visage',
    localized_name: 'Visage',
    primary_attr: HeroesPrimaryAttribute.INTELLIGENCE,
    attack_type: 'Ranged',
    roles: [
      HeroesRoles.SUPPORT,
      HeroesRoles.NUKER,
      HeroesRoles.DURABLE,
      HeroesRoles.DISABLER,
      HeroesRoles.PUSHER,
    ],
    legs: 2,
  },
  {
    id: 93,
    name: 'npc_dota_hero_slark',
    localized_name: 'Slark',
    primary_attr: HeroesPrimaryAttribute.AGILITY,
    attack_type: 'Melee',
    roles: [
      HeroesRoles.CARRY,
      HeroesRoles.ESCAPE,
      HeroesRoles.DISABLER,
      HeroesRoles.NUKER,
    ],
    legs: 2,
  },
  {
    id: 94,
    name: 'npc_dota_hero_medusa',
    localized_name: 'Medusa',
    primary_attr: HeroesPrimaryAttribute.AGILITY,
    attack_type: 'Ranged',
    roles: [HeroesRoles.CARRY, HeroesRoles.DISABLER, HeroesRoles.DURABLE],
    legs: 0,
  },
  {
    id: 95,
    name: 'npc_dota_hero_troll_warlord',
    localized_name: 'Troll Warlord',
    primary_attr: HeroesPrimaryAttribute.AGILITY,
    attack_type: 'Ranged',
    roles: [
      HeroesRoles.CARRY,
      HeroesRoles.PUSHER,
      HeroesRoles.DISABLER,
      HeroesRoles.DURABLE,
    ],
    legs: 2,
  },
  {
    id: 96,
    name: 'npc_dota_hero_centaur',
    localized_name: 'Centaur Warrunner',
    primary_attr: HeroesPrimaryAttribute.STRENGTH,
    attack_type: 'Melee',
    roles: [
      HeroesRoles.DURABLE,
      HeroesRoles.INITIATOR,
      HeroesRoles.DISABLER,
      HeroesRoles.NUKER,
      HeroesRoles.ESCAPE,
    ],
    legs: 4,
  },
  {
    id: 97,
    name: 'npc_dota_hero_magnataur',
    localized_name: 'Magnus',
    primary_attr: HeroesPrimaryAttribute.STRENGTH,
    attack_type: 'Melee',
    roles: [
      HeroesRoles.INITIATOR,
      HeroesRoles.DISABLER,
      HeroesRoles.NUKER,
      HeroesRoles.ESCAPE,
    ],
    legs: 4,
  },
  {
    id: 98,
    name: 'npc_dota_hero_shredder',
    localized_name: 'Timbersaw',
    primary_attr: HeroesPrimaryAttribute.STRENGTH,
    attack_type: 'Melee',
    roles: [HeroesRoles.NUKER, HeroesRoles.DURABLE, HeroesRoles.ESCAPE],
    legs: 2,
  },
  {
    id: 99,
    name: 'npc_dota_hero_bristleback',
    localized_name: 'Bristleback',
    primary_attr: HeroesPrimaryAttribute.STRENGTH,
    attack_type: 'Melee',
    roles: [
      HeroesRoles.CARRY,
      HeroesRoles.DURABLE,
      HeroesRoles.INITIATOR,
      HeroesRoles.NUKER,
    ],
    legs: 2,
  },
  {
    id: 100,
    name: 'npc_dota_hero_tusk',
    localized_name: 'Tusk',
    primary_attr: HeroesPrimaryAttribute.STRENGTH,
    attack_type: 'Melee',
    roles: [HeroesRoles.INITIATOR, HeroesRoles.DISABLER, HeroesRoles.NUKER],
    legs: 2,
  },
  {
    id: 101,
    name: 'npc_dota_hero_skywrath_mage',
    localized_name: 'Skywrath Mage',
    primary_attr: HeroesPrimaryAttribute.INTELLIGENCE,
    attack_type: 'Ranged',
    roles: [HeroesRoles.SUPPORT, HeroesRoles.NUKER, HeroesRoles.DISABLER],
    legs: 2,
  },
  {
    id: 102,
    name: 'npc_dota_hero_abaddon',
    localized_name: 'Abaddon',
    primary_attr: HeroesPrimaryAttribute.STRENGTH,
    attack_type: 'Melee',
    roles: [HeroesRoles.SUPPORT, HeroesRoles.CARRY, HeroesRoles.DURABLE],
    legs: 2,
  },
  {
    id: 103,
    name: 'npc_dota_hero_elder_titan',
    localized_name: 'Elder Titan',
    primary_attr: HeroesPrimaryAttribute.STRENGTH,
    attack_type: 'Melee',
    roles: [
      HeroesRoles.INITIATOR,
      HeroesRoles.DISABLER,
      HeroesRoles.NUKER,
      HeroesRoles.DURABLE,
    ],
    legs: 2,
  },
  {
    id: 104,
    name: 'npc_dota_hero_legion_commander',
    localized_name: 'Legion Commander',
    primary_attr: HeroesPrimaryAttribute.STRENGTH,
    attack_type: 'Melee',
    roles: [
      HeroesRoles.CARRY,
      HeroesRoles.DISABLER,
      HeroesRoles.INITIATOR,
      HeroesRoles.DURABLE,
      HeroesRoles.NUKER,
    ],
    legs: 2,
  },
  {
    id: 105,
    name: 'npc_dota_hero_techies',
    localized_name: 'Techies',
    primary_attr: HeroesPrimaryAttribute.INTELLIGENCE,
    attack_type: 'Ranged',
    roles: [HeroesRoles.NUKER, HeroesRoles.DISABLER],
    legs: 6,
  },
  {
    id: 106,
    name: 'npc_dota_hero_ember_spirit',
    localized_name: 'Ember Spirit',
    primary_attr: HeroesPrimaryAttribute.AGILITY,
    attack_type: 'Melee',
    roles: [
      HeroesRoles.CARRY,
      HeroesRoles.ESCAPE,
      HeroesRoles.NUKER,
      HeroesRoles.DISABLER,
      HeroesRoles.INITIATOR,
    ],
    legs: 2,
  },
  {
    id: 107,
    name: 'npc_dota_hero_earth_spirit',
    localized_name: 'Earth Spirit',
    primary_attr: HeroesPrimaryAttribute.STRENGTH,
    attack_type: 'Melee',
    roles: [
      HeroesRoles.NUKER,
      HeroesRoles.ESCAPE,
      HeroesRoles.DISABLER,
      HeroesRoles.INITIATOR,
      HeroesRoles.DURABLE,
    ],
    legs: 2,
  },
  {
    id: 108,
    name: 'npc_dota_hero_abyssal_underlord',
    localized_name: 'Underlord',
    primary_attr: HeroesPrimaryAttribute.STRENGTH,
    attack_type: 'Melee',
    roles: [
      HeroesRoles.SUPPORT,
      HeroesRoles.NUKER,
      HeroesRoles.DISABLER,
      HeroesRoles.DURABLE,
      HeroesRoles.ESCAPE,
    ],
    legs: 2,
  },
  {
    id: 109,
    name: 'npc_dota_hero_terrorblade',
    localized_name: 'Terrorblade',
    primary_attr: HeroesPrimaryAttribute.AGILITY,
    attack_type: 'Melee',
    roles: [HeroesRoles.CARRY, HeroesRoles.PUSHER, HeroesRoles.NUKER],
    legs: 2,
  },
  {
    id: 110,
    name: 'npc_dota_hero_phoenix',
    localized_name: 'Phoenix',
    primary_attr: HeroesPrimaryAttribute.STRENGTH,
    attack_type: 'Ranged',
    roles: [
      HeroesRoles.SUPPORT,
      HeroesRoles.NUKER,
      HeroesRoles.INITIATOR,
      HeroesRoles.ESCAPE,
      HeroesRoles.DISABLER,
    ],
    legs: 2,
  },
  {
    id: 111,
    name: 'npc_dota_hero_oracle',
    localized_name: 'Oracle',
    primary_attr: HeroesPrimaryAttribute.INTELLIGENCE,
    attack_type: 'Ranged',
    roles: [
      HeroesRoles.SUPPORT,
      HeroesRoles.NUKER,
      HeroesRoles.DISABLER,
      HeroesRoles.ESCAPE,
    ],
    legs: 0,
  },
  {
    id: 112,
    name: 'npc_dota_hero_winter_wyvern',
    localized_name: 'Winter Wyvern',
    primary_attr: HeroesPrimaryAttribute.INTELLIGENCE,
    attack_type: 'Ranged',
    roles: [HeroesRoles.SUPPORT, HeroesRoles.DISABLER, HeroesRoles.NUKER],
    legs: 2,
  },
  {
    id: 113,
    name: 'npc_dota_hero_arc_warden',
    localized_name: 'Arc Warden',
    primary_attr: HeroesPrimaryAttribute.AGILITY,
    attack_type: 'Ranged',
    roles: [HeroesRoles.CARRY, HeroesRoles.ESCAPE, HeroesRoles.NUKER],
    legs: 2,
  },
  {
    id: 114,
    name: 'npc_dota_hero_monkey_king',
    localized_name: 'Monkey King',
    primary_attr: HeroesPrimaryAttribute.AGILITY,
    attack_type: 'Melee',
    roles: [
      HeroesRoles.CARRY,
      HeroesRoles.ESCAPE,
      HeroesRoles.DISABLER,
      HeroesRoles.INITIATOR,
    ],
    legs: 2,
  },
  {
    id: 119,
    name: 'npc_dota_hero_dark_willow',
    localized_name: 'Dark Willow',
    primary_attr: HeroesPrimaryAttribute.INTELLIGENCE,
    attack_type: 'Ranged',
    roles: [
      HeroesRoles.SUPPORT,
      HeroesRoles.NUKER,
      HeroesRoles.DISABLER,
      HeroesRoles.ESCAPE,
    ],
    legs: 2,
  },
  {
    id: 120,
    name: 'npc_dota_hero_pangolier',
    localized_name: 'Pangolier',
    primary_attr: HeroesPrimaryAttribute.AGILITY,
    attack_type: 'Melee',
    roles: [
      HeroesRoles.CARRY,
      HeroesRoles.NUKER,
      HeroesRoles.DISABLER,
      HeroesRoles.DURABLE,
      HeroesRoles.ESCAPE,
      HeroesRoles.INITIATOR,
    ],
    legs: 2,
  },
  {
    id: 121,
    name: 'npc_dota_hero_grimstroke',
    localized_name: 'Grimstroke',
    primary_attr: HeroesPrimaryAttribute.INTELLIGENCE,
    attack_type: 'Ranged',
    roles: [
      HeroesRoles.SUPPORT,
      HeroesRoles.NUKER,
      HeroesRoles.DISABLER,
      HeroesRoles.ESCAPE,
    ],
    legs: 0,
  },
  {
    id: 123,
    name: 'npc_dota_hero_hoodwink',
    localized_name: 'Hoodwink',
    primary_attr: HeroesPrimaryAttribute.AGILITY,
    attack_type: 'Ranged',
    roles: [
      HeroesRoles.SUPPORT,
      HeroesRoles.NUKER,
      HeroesRoles.ESCAPE,
      HeroesRoles.DISABLER,
    ],
    legs: 4,
  },
  {
    id: 126,
    name: 'npc_dota_hero_void_spirit',
    localized_name: 'Void Spirit',
    primary_attr: HeroesPrimaryAttribute.INTELLIGENCE,
    attack_type: 'Melee',
    roles: [
      HeroesRoles.CARRY,
      HeroesRoles.ESCAPE,
      HeroesRoles.NUKER,
      HeroesRoles.DISABLER,
    ],
    legs: 2,
  },
  {
    id: 128,
    name: 'npc_dota_hero_snapfire',
    localized_name: 'Snapfire',
    primary_attr: HeroesPrimaryAttribute.STRENGTH,
    attack_type: 'Ranged',
    roles: [
      HeroesRoles.SUPPORT,
      HeroesRoles.NUKER,
      HeroesRoles.DISABLER,
      HeroesRoles.ESCAPE,
    ],
    legs: 2,
  },
  {
    id: 129,
    name: 'npc_dota_hero_mars',
    localized_name: 'Mars',
    primary_attr: HeroesPrimaryAttribute.STRENGTH,
    attack_type: 'Melee',
    roles: [
      HeroesRoles.CARRY,
      HeroesRoles.INITIATOR,
      HeroesRoles.DISABLER,
      HeroesRoles.DURABLE,
    ],
    legs: 2,
  },
  {
    id: 135,
    name: 'npc_dota_hero_dawnbreaker',
    localized_name: 'Dawnbreaker',
    primary_attr: HeroesPrimaryAttribute.STRENGTH,
    attack_type: 'Melee',
    roles: [HeroesRoles.CARRY, HeroesRoles.DURABLE],
    legs: 2,
  },
  {
    id: 136,
    name: 'npc_dota_hero_marci',
    localized_name: 'Marci',
    primary_attr: HeroesPrimaryAttribute.STRENGTH,
    attack_type: 'Melee',
    roles: [
      HeroesRoles.SUPPORT,
      HeroesRoles.CARRY,
      HeroesRoles.INITIATOR,
      HeroesRoles.DISABLER,
      HeroesRoles.ESCAPE,
    ],
    legs: 2,
  },
  {
    id: 137,
    name: 'npc_dota_hero_primal_beast',
    localized_name: 'Primal Beast',
    primary_attr: HeroesPrimaryAttribute.STRENGTH,
    attack_type: 'Melee',
    roles: [HeroesRoles.INITIATOR, HeroesRoles.DURABLE, HeroesRoles.DISABLER],
    legs: 2,
  },
];
